line-length = 120

[lint]
select = ["B", "N", "E", "ISC", "W", "F", "RET", "SIM", "PL", "C"]

[format]
quote-style = "single"

# Исключаем тесты и другие папки из анализа
exclude = [
    "tests",
    "venv",
    "migrations",
    "__pycache__",
]