"""migration_with_ruff_format

Revision ID: 07b6633fd0e8
Revises: f0ad791970c3
Create Date: 2025-12-26 14:09:19.786636

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '07b6633fd0e8'
down_revision: Union[str, Sequence[str], None] = 'f0ad791970c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
