name: Ruff

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
      - name: Run Ruff
        run: |
          uv sync --group dev --frozen
          uv run ruff format --check --exclude=tests .
          uv run ruff check --exclude=tests .